// Generated: the 56 Minor Arcana ids and English names, ordered
// Cups, Pentacles, Swords, Wands; ranks Ace..Ten, Page, Knight, Queen, King.
// Kept as a flat table so `Card` holds `&'static str` and stays `Copy`.

const MINOR_IDS: [&str; 56] = [
    "Cups01",
    "Cups02",
    "Cups03",
    "Cups04",
    "Cups05",
    "Cups06",
    "Cups07",
    "Cups08",
    "Cups09",
    "Cups10",
    "Cups11",
    "Cups12",
    "Cups13",
    "Cups14",
    "Pentacles01",
    "Pentacles02",
    "Pentacles03",
    "Pentacles04",
    "Pentacles05",
    "Pentacles06",
    "Pentacles07",
    "Pentacles08",
    "Pentacles09",
    "Pentacles10",
    "Pentacles11",
    "Pentacles12",
    "Pentacles13",
    "Pentacles14",
    "Swords01",
    "Swords02",
    "Swords03",
    "Swords04",
    "Swords05",
    "Swords06",
    "Swords07",
    "Swords08",
    "Swords09",
    "Swords10",
    "Swords11",
    "Swords12",
    "Swords13",
    "Swords14",
    "Wands01",
    "Wands02",
    "Wands03",
    "Wands04",
    "Wands05",
    "Wands06",
    "Wands07",
    "Wands08",
    "Wands09",
    "Wands10",
    "Wands11",
    "Wands12",
    "Wands13",
    "Wands14",
];

const MINOR_NAMES: [&str; 56] = [
    "Ace of Cups",
    "Two of Cups",
    "Three of Cups",
    "Four of Cups",
    "Five of Cups",
    "Six of Cups",
    "Seven of Cups",
    "Eight of Cups",
    "Nine of Cups",
    "Ten of Cups",
    "Page of Cups",
    "Knight of Cups",
    "Queen of Cups",
    "King of Cups",
    "Ace of Pentacles",
    "Two of Pentacles",
    "Three of Pentacles",
    "Four of Pentacles",
    "Five of Pentacles",
    "Six of Pentacles",
    "Seven of Pentacles",
    "Eight of Pentacles",
    "Nine of Pentacles",
    "Ten of Pentacles",
    "Page of Pentacles",
    "Knight of Pentacles",
    "Queen of Pentacles",
    "King of Pentacles",
    "Ace of Swords",
    "Two of Swords",
    "Three of Swords",
    "Four of Swords",
    "Five of Swords",
    "Six of Swords",
    "Seven of Swords",
    "Eight of Swords",
    "Nine of Swords",
    "Ten of Swords",
    "Page of Swords",
    "Knight of Swords",
    "Queen of Swords",
    "King of Swords",
    "Ace of Wands",
    "Two of Wands",
    "Three of Wands",
    "Four of Wands",
    "Five of Wands",
    "Six of Wands",
    "Seven of Wands",
    "Eight of Wands",
    "Nine of Wands",
    "Ten of Wands",
    "Page of Wands",
    "Knight of Wands",
    "Queen of Wands",
    "King of Wands",
];
